{
    "openapi": "3.0.0",
    "info": {
        "title": "API Gateway Documentation",
        "description": "This allows you to create,read, update and delete a product",
        "contact": {
            "email": "esekelvin24@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:8181/api/v1",
            "description": "API Gateway Server"
        }
    ],
    "paths": {
        "/login": {
            "post": {
                "tags": [
                    "Access Token"
                ],
                "summary": "Sign in",
                "description": "Login by email, password to get access token",
                "operationId": "authLogin",
                "requestBody": {
                    "description": "Account login credentials",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "email",
                                    "password"
                                ],
                                "properties": {
                                    "email": {
                                        "type": "string",
                                        "format": "email",
                                        "example": "user1@mail.com"
                                    },
                                    "password": {
                                        "type": "string",
                                        "format": "password",
                                        "example": "PassWord12345"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful Login",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "User login succesfully, Use token to authenticate."
                                        },
                                        "token": {
                                            "type": "string",
                                            "example": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiODQ3MThkNTZjZTZiYWI2OGFmNDgwZjlmNjA4NTA4NGU5M2NhY2JiMjRmZWU4ZWQzZGE0YTQ4OGQ1ZTRlM2NiN2RlNmRmN2VkYjY5ZjhjZjciLCJpYXQiOjE2NzQzNzg3MjEsIm5iZiI6MTY3NDM3ODcyMSwiZXhwIjoxNzA1OTE0NzIxLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.d7D4ZXHxRZ8D44noKOOtzkMBlYbd8sDMQLIxwlOHc_RAqG64SbuRHWQzg7DPG9WqlKiBFF53LxLT6lQScmml5uanneTVCB9LKdzMP9WpXDS1OHklepPgdiuXaWbvH5k226uDEl1QfCL3EJoFICRQE7CW-4UCsjpP08XOiIDblc2UnPdJWW6wyWgf0xS5VGAwTRc_PzWNLIWcustebWhT9Od9blVyz_yeyQ9fRKBBScHiWvcOKwfn1dHrMDmtlJsM_B4mR-csxez9Zun05SjyhegQI2Q1Ldi1SWshi4BSBm70DS3CuKBAdP5Py9aoNHjyM-4ow_z57ozbuRqTT3-6qPbNTW85zYSAS0g_VSkla2iyhiRN_GyiLwp7-F1iqvoElU1Os63popaYUo7Dbg3JSXQGbClXlCHMCFwaofDBgfuMmz-qAdiCFoYGqkWb9iZSjz57wRUuH3HoXYpJ7QfP-YwUGKMKdyEYsYdM9wz3jHwgZHUay-2YPQHFPhRwkm3wQwWkGH4C-n4PNprOJrXiTYIJqQ95WowEq0VY8Wljr_0RAb5_cJUtjlwIfafcTrXQkY6ZQ6NFikUlRLpDUDjSl9cDvQIxFoUuzlxwVGfSzy6PL-k4m_kTWABJeYb_lDLlF5AoDVBGum6h472jbhEiIspci9R7srWUw7S"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "tags": [
                    "User Creation"
                ],
                "summary": "Registration",
                "description": "To create a new user on the system",
                "operationId": "registration",
                "requestBody": {
                    "description": "User Details",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "name",
                                    "email",
                                    "password"
                                ],
                                "properties": {
                                    "firstname": {
                                        "type": "string",
                                        "format": "text",
                                        "example": "John"
                                    },
                                    "middlename": {
                                        "type": "string",
                                        "format": "text",
                                        "example": "Elfa"
                                    },
                                    "lastname": {
                                        "type": "string",
                                        "format": "text",
                                        "example": "Emmanuel"
                                    },
                                    "email": {
                                        "type": "string",
                                        "format": "email",
                                        "example": "user1@mail.com"
                                    },
                                    "password": {
                                        "type": "string",
                                        "format": "password",
                                        "example": "PassWord12345"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful Registration",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "User registered succesfully, Use Login method to receive token."
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/articles": {
            "get": {
                "tags": [
                    "Lis of created articles"
                ],
                "summary": "View List of article",
                "description": "To Display all article",
                "operationId": "articles_view",
                "responses": {
                    "200": {
                        "description": "Successful Product Update",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "id": {
                                            "type": "string",
                                            "example": "1"
                                        },
                                        "cover": {
                                            "type": "string",
                                            "example": "https://imgd.aeplcdn.com/1200x900/n/cw/ec/110233/2022-camry-exterior-right-front-three-quarter.jpeg?isig=0&q=75"
                                        },
                                        "full_text": {
                                            "type": "string",
                                            "example": "jdsndj  ksjdnkjn kjsnd"
                                        },
                                        "likes": {
                                            "type": "integer",
                                            "example": "0"
                                        },
                                        "views": {
                                            "type": "integer",
                                            "example": "0"
                                        },
                                        "created_at": {
                                            "type": "string",
                                            "example": "2023-01-22T13:33:14.000000Z"
                                        },
                                        "updated_at": {
                                            "type": "string",
                                            "example": "2023-01-22T13:33:14.000000Z"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Create new article"
                ],
                "summary": "Add Article",
                "description": "To create a new article on the system",
                "operationId": "add_article",
                "requestBody": {
                    "description": "Article Information",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "name",
                                    "email",
                                    "password"
                                ],
                                "properties": {
                                    "full_text": {
                                        "type": "string",
                                        "format": "text",
                                        "example": "A test Article"
                                    },
                                    "cover": {
                                        "type": "string",
                                        "format": "text",
                                        "example": "https://imgd.aeplcdn.com/1200x900/n/cw/ec/110233/2022-camry-exterior-right-front-three-quarter.jpeg?isig=0&q=75"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful Registration",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "Your article has been created"
                                        },
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string",
                                                "example": {
                                                    "full_text": "Test Article",
                                                    "cover": "http://picture.com/1.jpg",
                                                    "created_at": "2023-01-22T13:33:14.000000Z",
                                                    "id": 1
                                                }
                                            },
                                            "collectionFormat": "multi"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/articles/{article_id}": {
            "get": {
                "tags": [
                    "View article by article ID"
                ],
                "summary": "View article using id",
                "description": "To display article when an article id is inserted",
                "operationId": "view_article",
                "parameters": [
                    {
                        "name": "article_id",
                        "in": "path",
                        "description": "Article id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Article",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "id": {
                                            "type": "string",
                                            "example": "1"
                                        },
                                        "cover": {
                                            "type": "string",
                                            "example": "https://imgd.aeplcdn.com/1200x900/n/cw/ec/110233/2022-camry-exterior-right-front-three-quarter.jpeg?isig=0&q=75"
                                        },
                                        "full_text": {
                                            "type": "string",
                                            "example": "jdsndj  ksjdnkjn kjsnd"
                                        },
                                        "likes": {
                                            "type": "integer",
                                            "example": "0"
                                        },
                                        "views": {
                                            "type": "integer",
                                            "example": "0"
                                        },
                                        "created_at": {
                                            "type": "string",
                                            "example": "2023-01-22T13:33:14.000000Z"
                                        },
                                        "updated_at": {
                                            "type": "string",
                                            "example": "2023-01-22T13:33:14.000000Z"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/articles/{article_id}/comments": {
            "get": {
                "tags": [
                    "View article comments by article ID"
                ],
                "summary": "View article comments using id",
                "description": "To display article and it's comments when an article id is inserted",
                "operationId": "view_article_comment",
                "parameters": [
                    {
                        "name": "article_id",
                        "in": "path",
                        "description": "Article id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "View Article comments",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "Successful"
                                        },
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string",
                                                "example": {
                                                    "id": 1,
                                                    "article_id": 1,
                                                    "comments": "Testing comment",
                                                    "created_at": "2023-01-22T13:33:14.000000Z"
                                                }
                                            },
                                            "collectionFormat": "multi"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Add comments to article"
                ],
                "summary": "add article comments using id",
                "description": "To add comments to an article when an article id is inserted",
                "operationId": "insert_new_article_comment",
                "parameters": [
                    {
                        "name": "article_id",
                        "in": "path",
                        "description": "Article id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "description": "User Details",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "comments"
                                ],
                                "properties": {
                                    "comments": {
                                        "type": "string",
                                        "format": "text",
                                        "example": "Testing comment insert"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Add Comments to Article",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "Your comments have been added to this article"
                                        },
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string",
                                                "example": {
                                                    "article_id": 1,
                                                    "comments": "Testing comment",
                                                    "created_at": "2023-01-22T13:33:14.000000Z",
                                                    "id": 1
                                                }
                                            },
                                            "collectionFormat": "multi"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/articles/{article_id}/likes": {
            "get": {
                "tags": [
                    "Show List of Like"
                ],
                "summary": "Show List of Article likes",
                "description": "Show list of likes on an article",
                "operationId": "show_like",
                "parameters": [
                    {
                        "name": "article_id",
                        "in": "path",
                        "description": "Article id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Show Likes",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "total number of like"
                                        },
                                        "data": {
                                            "type": "string",
                                            "example": "2"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Like an article"
                ],
                "summary": "Like an article",
                "description": "To like an article",
                "operationId": "article_like",
                "parameters": [
                    {
                        "name": "article_id",
                        "in": "path",
                        "description": "Article id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "You just like this article",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "id": {
                                            "type": "string",
                                            "example": "1"
                                        },
                                        "cover": {
                                            "type": "string",
                                            "example": "https://imgd.aeplcdn.com/1200x900/n/cw/ec/110233/2022-camry-exterior-right-front-three-quarter.jpeg?isig=0&q=75"
                                        },
                                        "full_text": {
                                            "type": "string",
                                            "example": "jdsndj  ksjdnkjn kjsnd"
                                        },
                                        "likes": {
                                            "type": "integer",
                                            "example": "0"
                                        },
                                        "views": {
                                            "type": "integer",
                                            "example": "0"
                                        },
                                        "created_at": {
                                            "type": "string",
                                            "example": "2023-01-22T13:33:14.000000Z"
                                        },
                                        "updated_at": {
                                            "type": "string",
                                            "example": "2023-01-22T13:33:14.000000Z"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/articles/{article_id}/views": {
            "get": {
                "tags": [
                    "Show List of views"
                ],
                "summary": "Show List of Article views",
                "description": "Show list of views on an article",
                "operationId": "show_views",
                "parameters": [
                    {
                        "name": "article_id",
                        "in": "path",
                        "description": "Article id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Show Views",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "total number of views"
                                        },
                                        "data": {
                                            "type": "string",
                                            "example": "2"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "View an article"
                ],
                "summary": "To view an article",
                "description": "View article",
                "operationId": "article_view",
                "parameters": [
                    {
                        "name": "article_id",
                        "in": "path",
                        "description": "Article id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "You just view this article",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "id": {
                                            "type": "string",
                                            "example": "1"
                                        },
                                        "cover": {
                                            "type": "string",
                                            "example": "https://imgd.aeplcdn.com/1200x900/n/cw/ec/110233/2022-camry-exterior-right-front-three-quarter.jpeg?isig=0&q=75"
                                        },
                                        "full_text": {
                                            "type": "string",
                                            "example": "jdsndj  ksjdnkjn kjsnd"
                                        },
                                        "likes": {
                                            "type": "integer",
                                            "example": "0"
                                        },
                                        "views": {
                                            "type": "integer",
                                            "example": "0"
                                        },
                                        "created_at": {
                                            "type": "string",
                                            "example": "2023-01-22T13:33:14.000000Z"
                                        },
                                        "updated_at": {
                                            "type": "string",
                                            "example": "2023-01-22T13:33:14.000000Z"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        }
    },
    "components": {
        "responses": {
            "401": {
                "description": "Wrong credentials response",
                "content": {
                    "application/json": {
                        "schema": {
                            "properties": {
                                "success": {
                                    "type": "boolean",
                                    "example": "false"
                                },
                                "message": {
                                    "type": "string",
                                    "example": "User authentication failed."
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            },
            "402": {
                "description": "Wrong credentials response",
                "content": {
                    "application/json": {
                        "schema": {
                            "properties": {
                                "success": {
                                    "type": "boolean",
                                    "example": "false"
                                },
                                "message": {
                                    "type": "string",
                                    "example": "User authentication failed."
                                }
                            },
                            "type": "object"
                        }
                    }
                }
            }
        },
        "securitySchemes": {
            "bearer_token": {
                "type": "apiKey",
                "description": "Enter token in format (Bearer <token>)",
                "name": "Authorization",
                "in": "header"
            }
        }
    },
    "tags": [
        {
            "name": "Projects",
            "description": "API Endpoints of Articles"
        }
    ]
}